before_script:
  - apt-get update -qq && apt-get -y install libcunit1 libcunit1-doc libcunit1-dev libjansson-dev graphviz
  - git clone https://github.com/sstephenson/bats.git /tmp/bats
  - mkdir -p /tmp/local
  - bash /tmp/bats/install.sh /tmp/local
  - export PATH=$PATH:/tmp/local/bin

build:
    stage: build
    script:
    - make data 
    
test:
    stage: test
    script:
    - make
    - make test

